# Generated by Django 5.1.5 on 2025-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('categorie', models.CharField(choices=[('Film', 'Film'), ('Jeux-vidéo', 'Jeux Vidéo'), ('Livre', 'Livre')], max_length=30)),
                ('etiquette', models.CharField(choices=[('Action', 'Action'), ('Eprouvante', 'Eprouvante'), ('Fantaisie', 'Fantaisie'), ('Fantastique', 'Fantastique'), ('Horreur', 'Horreur'), ('Policier', 'Policier'), ('Romance', 'Romance')], max_length=30, null=True)),
            ],
        ),
    ]
