# Generated by Django 5.1.5 on 2025-02-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_etiquette_alter_article_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='Image'),
        ),
    ]
