# Generated by Django 5.1.5 on 2025-02-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
