# Generated by Django 5.1.5 on 2025-03-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Description article'),
        ),
    ]
