# Generated by Django 5.1.5 on 2025-03-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_alter_article_image_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaire', to='blogApp.article', verbose_name='Article'),
        ),
    ]
