# Generated by Django 5.1.5 on 2025-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0012_alter_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='date_dreation',
            new_name='date_reaction',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='message_com',
            field=models.CharField(max_length=200, verbose_name='Commentaire'),
        ),
    ]
