# Generated by Django 5.1.5 on 2025-03-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0014_alter_commentaire_user_com'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='user_com',
            new_name='user',
        ),
    ]
