# Generated by Django 5.1.5 on 2025-03-27 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0015_rename_user_com_commentaire_user'),
        ('user', '0002_alter_userprofil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofil', verbose_name='Auteur'),
        ),
    ]
