# Generated by Django 5.1.5 on 2025-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='user_image',
            field=models.ImageField(upload_to='image_profil/'),
        ),
    ]
