# Generated by Django 5.1.5 on 2025-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofil_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='user_image',
            field=models.ImageField(default='Image/cuisine-asiatique-dans-restaurant_7939-2004.jpg', upload_to='image_profil/'),
            preserve_default=False,
        ),
    ]
